In [1]:
import numpy as np

In [69]:
gen_fact = [[] for i in range (2)]
gen_fact

[[], []]

In [70]:
gen_fact = [[] for i in range (2)]

for i in range (10000):
    gen_fact[np.random.randint(0,2,1)[0]].append(1)

In [71]:
factory = [ sum(i) for i in gen_fact]

In [72]:
factory

[4938, 5062]

In [73]:
sum(factory)

10000

In [74]:
gen_rej = [[] for i in range (2)]
for i in range(1000):
    gen_rej[np.random.randint(0,2,1)[0]].append(1)
rejection  = [ sum(i) for i in gen_rej]


In [75]:
factory = np.array(factory)

In [76]:
factory

array([4938, 5062])

In [79]:
rejection = np.array(rejection)

In [80]:
rejection

array([518, 482])

In [81]:
factory

array([4938, 5062])

In [82]:
rejection

array([518, 482])

In [83]:
s = 1/2*(518/4938)

In [84]:
s1 = sum((1/2)*rejection/factory)

In [86]:
s/s1

0.5241892019402539

In [65]:
s/s1

0.03905014778308718