In [61]:
import numpy as np
import collections as c

In [62]:
pop_size = 1000
pop = np.random.randint(1,3,pop_size)
pop

array([2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 1,
       1, 2, 1, 1, 2, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 2,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2,
       1, 2, 1, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1,
       1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 1, 1, 2, 1, 1,
       1, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2,
       2, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 1, 1,
       1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2,
       1, 1, 2, 1, 2, 2, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 2,
       1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 2, 2,
       1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 1, 1, 2, 1,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2,

In [63]:
pop_count= c.Counter(pop)
pop_count[1]/1000

0.481

In [64]:
sample_size = 30
sample_dist = [np.random.choice(pop,sample_size) for i in range(100)]
sample_dist

[array([1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1,
        1, 1, 2, 2, 1, 2, 1, 1]),
 array([2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 1,
        1, 1, 2, 2, 2, 1, 1, 2]),
 array([2, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1,
        1, 1, 1, 2, 1, 2, 1, 1]),
 array([1, 1, 2, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2,
        1, 2, 2, 2, 1, 1, 1, 1]),
 array([1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2,
        2, 2, 2, 1, 2, 2, 2, 1]),
 array([1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1,
        2, 1, 1, 2, 2, 1, 2, 1]),
 array([2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 2,
        1, 2, 1, 2, 1, 2, 1, 2]),
 array([1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2,
        2, 1, 2, 1, 1, 1, 1, 1]),
 array([1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1,
        2, 1, 2, 1, 2, 2, 1, 2]),
 array([2, 1, 1, 1, 1, 2, 2,

In [65]:
sample_dist_count = [c.Counter(sample_dist[i]) for i in range (100)]
sample_dist_count

[Counter({1: 20, 2: 10}),
 Counter({1: 12, 2: 18}),
 Counter({1: 18, 2: 12}),
 Counter({1: 13, 2: 17}),
 Counter({1: 11, 2: 19}),
 Counter({1: 18, 2: 12}),
 Counter({1: 17, 2: 13}),
 Counter({1: 18, 2: 12}),
 Counter({1: 14, 2: 16}),
 Counter({1: 17, 2: 13}),
 Counter({1: 12, 2: 18}),
 Counter({1: 15, 2: 15}),
 Counter({1: 15, 2: 15}),
 Counter({1: 12, 2: 18}),
 Counter({1: 15, 2: 15}),
 Counter({1: 14, 2: 16}),
 Counter({1: 14, 2: 16}),
 Counter({1: 15, 2: 15}),
 Counter({1: 16, 2: 14}),
 Counter({1: 12, 2: 18}),
 Counter({1: 11, 2: 19}),
 Counter({1: 17, 2: 13}),
 Counter({1: 13, 2: 17}),
 Counter({1: 13, 2: 17}),
 Counter({1: 15, 2: 15}),
 Counter({1: 12, 2: 18}),
 Counter({1: 20, 2: 10}),
 Counter({1: 14, 2: 16}),
 Counter({1: 16, 2: 14}),
 Counter({1: 13, 2: 17}),
 Counter({1: 15, 2: 15}),
 Counter({1: 12, 2: 18}),
 Counter({1: 13, 2: 17}),
 Counter({1: 11, 2: 19}),
 Counter({1: 15, 2: 15}),
 Counter({1: 15, 2: 15}),
 Counter({1: 15, 2: 15}),
 Counter({1: 12, 2: 18}),
 Counter({1:

In [66]:
sample_dist_count_1 = [i[1]/sample_size for i in sample_dist_count]

In [67]:
sample_dist_count_2 = [i[2]/sample_size for i in sample_dist_count]

In [68]:
sum(sample_dist_count_1)/ 100 , sum(sample_dist_count_2)/ 100

(0.4783333333333333, 0.5216666666666667)